### ISSUE TITLE
Load Addon won't disappear

### ISSUE THREAD

**Issue by Reebus** [MrJul/ToS-EnhancedCollection#4]
When I add dofile("../addons/enhancedcollection/enhancedcollection.lua"); to addonloader.lua and start up the game, then press Load Addon, it stays on the screen.

**Comment by MrJul** [comment]
Please install v1.1.0 which is a simple IPF file copy, no more file editing needed!
Instructions are in the [readme file](https://github.com/MrJul/ToS-EnhancedCollection/blob/master/README.md).
